---
- name: "Get Nexus password"
  shell: |
    #!/bin/bash
    oc get pods -n {{ nexus_namespace }} | grep nexus-1 | grep -v deploy | awk '{print $1}'
  register: nexus_podname
  ignore_errors: false
  when:
  - nexus_password is not defined or nexus_password|trim == ''

- name: Getting nexus pod name
  set_fact:
    nexus_pod: "{{ nexus_podname.stdout }}"
  when:
  - nexus_password is not defined or nexus_password|trim == ''

- name: display nexus pod name
  debug:
    msg: Generated {{ nexus_pod }}

- name: "Get Nexus password"
  shell: |
    #!/bin/bash
    oc exec -it {{ nexus_pod }} /usr/bin/cat /nexus-data/admin.password  -n {{ nexus_namespace }}
  register: nexus_default_password
  when:
  - nexus_password is not defined or nexus_password|trim == ''

- name: setting default nexus password 
  set_fact:
    nexus_password: "{{ nexus_default_password.stdout }}"
  when:
  - nexus_password is not defined or nexus_password|trim == ''

- name: display nexus password
  debug:
    msg: Generated {{ nexus_password }}

- name: "Look up Nexus URL"
  command: >
    oc get route {{ nexus_name | default('nexus') }} -n {{ nexus_namespace }} -o custom-columns=ROUTE:.spec.host --no-headers
  register: nexus_url_result
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Set nexus_url Result"
  set_fact:
    nexus_url: "{{ nexus_url_result.stdout }}"
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Ensure Nexus is available before attempting to communicate"
  include_tasks: wait-for-nexus.yml

- name: "Configure Repos"
  include_tasks: configure-repos.yml
  with_items:
  - "{{ nexus_repos | default([]) }}"

